music/urls.py
from django.urls import path
from music import views

app_name = 'music'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('songs/', views.SongView.as_view(), name='songs'),
    path('album/add/', views.AlbumCreateView.as_view(), name='album-add'),
    path('album/<pk>/update/', views.AlbumUpdateView.as_view(), name='album-update'),
    path('album/<pk>/favorite/', views.establish_favorite_album, name='album-favorite'),
    path('album/<pk>/delete/', views.AlbumDeleteView.as_view(), name='album-delete'),
    path('album/<pk>/detail/', views.AlbumDetailVew.as_view(), name='detail'),
    path('song/<pk>/add/', views.SongCreateView.as_view(), name='song-add'),
    path('song/<pk>/<song_id>/update/', views.SongUpdateView.as_view(), name='song-update'),
    path('song/<pk>/<song_id>/favorite/', views.establish_favorite_song, name='song-favorite'),
    path('song/<pk>/<song_id>/delete/', views.SongDeleteView.as_view(), name='song-delete'),
    path('search/', views.SearchListView.as_view(), name='search')
]

network/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('posts/', include('posts.urls')),
    path('accounts/', include('allauth.urls')),
    path('messenger/', include('messenger.urls')),
    path('gallery/', include('gallery.urls')),
    path('music/', include('music.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
from django.db import models
from users.models import Profile
from django.urls import reverse


class Album(models.Model):
    """
    Class for music album which contains songs
    """
    title = models.CharField(max_length=200, db_index=True)
    artist = models.CharField(max_length=300, db_index=True)
    year = models.CharField(max_length=4)
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    logo = models.ImageField(upload_to='images/')
    is_favorite = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse("music:detail", kwargs={'pk': self.pk})

    def __str__(self):
        return f"{self.title} - {self.artist} - {self.year}"


class Song(models.Model):
    """
    Class for songs in album
    """
    title = models.CharField(max_length=300)
    file = models.FileField(upload_to='songs/', default='')
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    track_number = models.IntegerField(default=1)
    is_favorite = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse("music:detail", kwargs={'pk': self.album.id})

    def __str__(self):
        return self.title

music/views.py
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import (
    CreateView, UpdateView,
    DeleteView, ListView,
    DetailView
)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.db.models import Q
from music.models import Album, Song
from users.models import Profile


class IndexView(LoginRequiredMixin, ListView):
    template_name = 'music/index.html'
    context_object_name = "all_albums"

    def get_queryset(self):
        return Album.objects.filter(user__user=self.request.user)


class SongView(LoginRequiredMixin, ListView):
    template_name = 'music/songs.html'
    context_object_name = 'all_songs'

    def get_queryset(self):
        return Song.objects.all()

class AlbumDetailVew(LoginRequiredMixin, DetailView):
    model = Album
    template_name = 'music/detail.html'

    def get_context_data(self, **kwargs):
        context = super(AlbumDetailVew, self).get_context_data(**kwargs)
        context['link_detail'] = True
        context['header_text'] = 'All songs'
        return context

class AlbumCreateView(LoginRequiredMixin, CreateView):
    model = Album
    fields = ['title', 'artist', 'year', 'logo']

    def form_valid(self, form):
        profile = Profile.objects.get(user=self.request.user)
        obj = form.save(commit=False)
        form.instance.user = profile
        obj.save()
        return super().form_valid(form)


class AlbumUpdateView(LoginRequiredMixin, UpdateView):
    model = Album
    template_name = 'music/detail_form.html'
    fields = ['title', 'artist', 'year', 'logo', 'is_favorite']

    def get_context_data(self, **kwargs):
        context = super(AlbumUpdateView, self).get_context_data(**kwargs)
        context['link_album_update'] = True
        context['header_text'] = "Edit album details"
        return context

class AlbumDeleteView(LoginRequiredMixin, DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')

@login_required
def establish_favorite_album(request, **kwargs):
    album = get_object_or_404(Album, pk=kwargs['pk'])
    try:
        album.is_favorite = not album.is_favorite
        album.save()
    except(KeyError, Album.DoesNotExist):
        return HttpResponse('Album not found')

    else:
        return redirect('music:index')

class SongCreateView(LoginRequiredMixin, CreateView):
    model = Song
    template_name = 'music/detail_form.html'
    fields = ['title', 'file', 'track_number', 'is_favorite']

    def get_context_data(self, **kwargs):
        album_number = self.kwargs['pk']
        context = super(SongCreateView, self).get_context_data(**kwargs)
        context['album'] = Album.objects.get(id=album_number)
        context['link_song_create'] = True
        context['header_text'] = 'Add a new song'
        return context

    def form_valid(self, form):
        # profile = Profile.objects.get(user=self.request.user)
        album_number = self.kwargs['pk']
        # form.instance.user = profile
        form.instance.album = Album.objects.get(id=album_number)
        return super(SongCreateView, self).form_valid(form)


class SongUpdateView(LoginRequiredMixin, UpdateView):
    model = Song
    pk_url_kwarg = 'song_id'
    template_name = 'music/detail_form.html'
    fields = ['title', 'file', 'track_number', 'is_favorite']

    def get_context_data(self, **kwargs):
        album_number = self.kwargs['pk']
        context = super(SongUpdateView, self).get_context_data(**kwargs)
        context['album'] = Album.objects.get(id=album_number)
        context['link_song_update'] = True
        context['header_text'] = 'Edit song details'
        return context

class SongDeleteView(LoginRequiredMixin, DeleteView):
    model = Song
    pk_url_kwarg = 'song_id'
    def get_success_url(self):
        return reverse_lazy("music:detail", kwargs={'pk': self.kwargs['pk']})

@login_required
def establish_favorite_song(request, **kwargs):
    song = get_object_or_404(Song, pk=kwargs['pk'])
    try:
        song.is_favorite = not song.is_favorite
        song.save()
    except (KeyError, Song.DoesNotExist):
        return HttpResponse("Song not found.")
    else:
        return redirect('music:detail', pk=kwargs['pk'])

class SearchListView(ListView):
    template_name = "music/search.html"
    context_object_name = 'results'

    def get_queryset(self):
        query = self.request.GET.get('q')

        if query:
            search_results = Song.objects.filter(
                Q(album__artist__icontains=query) |
                Q(album__title__icontains=query) |
                Q(album__year__icontains=query) |
                Q(title__icontains=query)
            )
            return search_results

music/templates/music/album_form.html
{% extends 'main/base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block title %}Add a new album{% endblock %}
{% block add_albums_active %}active{% endblock %}

{% block content %}
{% bootstrap_css %}
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-12 col-md-7">
			<div class="panel panel-default">
				<div class="panel-body">
					<h3>Add a new album</h3>
					{% if error_message %}
						<p><strong>{{ error_message }}</strong></p>
					{% endif %}

					<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
						{% csrf_token %}
						{% include 'music/form-template.html' %}
						<div class="form-group">
							<div class="col-sm-offset-2 col-sm-10">
								<button type="submit" class="btn btn-success">Submit</button>
							</div>
						</div>
					</form>

				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

music/templates/music/detail-base.html
{% extends 'main/base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block title %}{{ album }}{% endblock %}

{% block content %}
{% bootstrap_css %}
<div class="container-fluid songs-container">
	<div class="row">


		<!-- Left Album Info -->
		<div class="col-sm-4 col-md-3">
			<div class="panel panel-default">
				<div class="panel-body">
					<a href="{% url 'music:detail' album.id %}">
						{% if album.logo %}
							<img src="{{ album.logo.url }}" class="img-responsive center-block">
						{% else %}
							<h3>No image to display</h3>
						{% endif %}
					</a>
					<div class="album-info">
						<h1>{{ album.title }}</h1>
						<h2>{{ album.artist }}</h2>
						<p>{{ album.year }}</p>
					</div>
				</div>
			</div>
		</div>


		<!-- Right Song Info -->
		<div class="col-sm-8 col-md-9">
			<ul class="nav nav-pills" style="margin-bottom:10px;">
				<li role="presentation" class="{% if link_detail %}active{% endif %}">
					<a class="btn btn-default" href="{% url 'music:detail' pk=album.id %}">View All</a></li>
				<li role="presentation" class="{% if link_song_create %}active{% endif %}">
					<a class="btn btn-default" href="{% url 'music:song-add' pk=album.id %}">Add New Song</a></li>
				<li role="presentation" class="{% if link_album_update %}active{% endif %}">
					<a class="btn btn-default" href="{% url 'music:album-update' pk=album.id %}">Edit Album Info</a></li>
				<li role="presentation" class="{% if link_song_update %}active{% endif %}">
					<a class="btn btn-default" href="#">Edit Song Info</a></li>
			</ul>

			<div class="panel panel-default">
				<div class="panel-body">
					{% block detail_body %}
					{% endblock %}
				</div>
			</div>
		</div>


	</div>
</div>
{% endblock %}

music/templates/music/detail.html
{% extends 'music/detail-base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block albums_active %}active{% endblock %}

<!-- Right Song Info -->
{% block content %}
{% bootstrap_css %}

<h3>{{ header_text }}</h3>
{% if error_message %}
	<p><strong>{{ error_message }}</strong></p>
{% endif %}

<table class="table">
	<thead>
		<tr>
			<td>Track #</td>
			<td>Title</td>
			<td>Favorite</td>
			<td>Play</td>
			<td>Edit</td>
			<td>Actions</td>
		</tr>
	</thead>
	<tbody>
		{% for song in album.song_set.all %}
			<tr>
				<td>{{ song.track_number }}</td>
				<td>{{ song.title }}</td>
				<td>
					<a href="{% url 'music:song-favorite' pk=album.id song_id=song.id %}" class="btn-favorite">
						<span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span>
					</a>
				</td>
				<td>
					{% if song.file %}
						<audio controls>
							<source src="{{ song.file.url }}">
						</audio>
					{% else %}
						No file uploaded.
					{% endif %}
				</td>
				<td>
					<a href="{% url 'music:song-update' pk=album.id song_id=song.id %}">
						<button type="button" class="btn btn-warning btn-xs">
							<span class="glyphicon glyphicon-pencil"> Edit</span>
						</button>
					</a>
				</td>
				<td>
					<form action="{% url 'music:song-delete' pk=album.id song_id=song.id %}" method="post" style="display:inline;">
						{% csrf_token %}
						<button type="submit" class="btn btn-danger btn-xs">
							<span class="glyphicon glyphicon-remove"> Delete</span>
						</button>
					</form>
				</td>
			</tr>
		{% endfor %}
	</tbody>
</table>
<a class="btn btn-primary" href="{% url 'music:song-add' pk=album.id %}">Add A New Song</a></li>

{% endblock %}

music/templates/music/detail_form.html
{% extends 'music/detail-base.html' %}
{% block albums_active %}active{% endblock %}
{% load static %}
{% load bootstrap4 %}

<!-- Right Song Info -->
{% block content %}
{% bootstrap_css %}

<h3>{{ header_text }}</h3>

{% if error_message %}
	<p><strong>{{ error_message }}</strong></p>
{% endif %}

<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
	{% csrf_token %}
	{% include 'music/form-template.html' %}
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<button type="submit" class="btn btn-success">Submit</button>
			<button type="reset" class="btn btn-warning">Reset</button>
		</div>
	</div>
</form>

{% endblock%}

music/templates/music/form-template.html
{% for field in form %}
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<span class="text-danger small">{{ field.errors }}</span>
		</div>
		<label class="control-label col-sm-2">{{ field.label_tag }}</label>
		<div class="col-sm-10">{{ field }}</div>
	</div>
{% endfor %}

music/templates/music/index.html
{% extends 'main/base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block albums_active %}active{% endblock %}
{% block title %}Albums{% endblock title %}

{% block content %}
{% bootstrap_css %}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>
<script src="https://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"></script>
<script src="https://threejs.org/examples/js/libs/stats.min.js"></script>
<script src="{% static 'music.js' %}"></script>

<script src="https://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"></script>
<section class="section home-5-bg" id="home">
    <div id="particles-js"></div>
    <div class="bg-overlay"></div>
    <div class="home-center">
        <div class="home-desc-center">
            <div class="container">
                <div class="justify-content-center row">
                    <div class="col-lg-7">
                        <div class="mt-40 text-center home-5-content">
                            <div class="home-icon mb-4"><i class="mdi mdi-pinwheel mdi-spin text-white h1"></i></div>
                            <h1 class="text-white font-weight-normal home-5-title mb-0">With your favorite music everywhere and anytime</h1>
                            <p class="text-white-70 mt-4 f-15 mb-0">Add new music to create your fantastic compilation of your favorite songs</p>
                            <div class="mt-5">
<!--                                <input class="btn btn-default" type="button" value="Get started right now">-->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% if user.is_authenticated%}
<!--          <h3>{{user.username}}'s Albums</h3>-->
        {% else %}
          <h3>All albums</h3>
        {% endif %}
  <div class="row py-5">

    </div>
    <!-- End -->

    <div class="row">
      {% if all_albums %}
        {% for album in all_albums %}
      <!-- Gallery item -->
          <div class="col-xl-3 col-lg-4 col-md-6 mb-4">
            <div class="bg-white rounded shadow-sm"><img src="{{album.logo.url}}" alt="" class="img-fluid card-img-top">
              <div class="p-4">
                <h5> <a href="#" class="text-dark">Album: {{album.title}}</a></h5>
                <h5> <a href="#" class="text-dark">Artist: {{album.artist}}</a></h5>
                <h5> <a href="#" class="text-dark">Year: {{album.year}}</a></h5>
                <div class="btn-group">
                      <a href="{% url 'music:detail' album.id %}" class="btn btn-sm btn-outline-primary" role="button">View Details</a>
                      <a class="btn btn-sm btn-outline-info" href="{% url 'music:album-update' pk=album.id %}" role="button">Edit Album</a></li>
                      <form action="{% url 'music:album-delete' album.id %}" method="post" style="display:inline;">
                        {% csrf_token %}
                        <input type="hidden" name="album_id" value="{{ album.id }}" />
                        <button type="submit" class="btn btn-default btn-sm btn-danger"><span class="glyphicon glyphicon-trash">Delete</span></button>
                      </form>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      {% endif %}
      <!-- End -->
    </div>
    <div class="py-5 text-right"><a href="{% url 'music:album-add' %}" class="btn btn-primary px-5 py-3 text-uppercase">Add a new album</a></div>

  </div>
</div>
{% endblock content %}

{% block scripts %}
    <script>
        particlesJS("particles-js", {
        "particles": {
            "number": {
                "value": 80,
                "density": {
                    "enable": true,
                    "value_area": 800
                }
            },
            "color": {
                "value": "#ffffff"
            },
            "shape": {
                "type": "circle",
                "stroke": {
                    "width": 0,
                    "color": "#000000"
            },
            "polygon": {
                "nb_sides": 5
             },
            "image": {
                "src": "img/github.svg",
                "width": 100,
                "height": 100
            }
        },
        "opacity": {
            "value": 0.5,
            "random": false,
            "anim": {
                "enable": false,
                "speed": 1,
                "opacity_min": 0.1,
                "sync": false
            }
        },
        "size": {
            "value": 20,
            "random": true,
            "anim": {
                "enable": false,
                "speed": 40,
                "size_min": 0.1,
                "sync": false
            }
        },
        "line_linked": {
            "enable": true,
            "distance": 150,
            "color": "#ffffff",
            "opacity": 0.22,
            "width": 1
        },
        "move": {
            "enable": true,
            "speed": 6,
            "direction": "none",
            "random": false,
            "straight": false,
            "out_mode": "out",
            "attract": {
                "enable": false,
                "rotateX": 600,
                "rotateY": 1200
            }
        }
    },
    "interactivity": {
        "detect_on": "canvas",
        "events": {
            "onhover": {
            "enable": true,
            "mode": "repulse"
        },
        "onclick": {
            "enable": true,
            "mode": "push"
        },
        "resize": true
    },
    "modes": {
      "grab": {
        "distance": 400,
        "line_linked": {
          "opacity": 1
        }
      },
      "bubble": {
        "distance": 400,
        "size": 40,
        "duration": 2,
        "opacity": 8,
        "speed": 3
      },
      "repulse": {
        "distance": 200
      },
      "push": {
        "particles_nb": 4
      },
      "remove": {
        "particles_nb": 2
      }
    }
  },
  "retina_detect": true,
  "config_demo": {
    "hide_card": false,
    "background_color": "#b61924",
    "background_image": "",
    "background_position": "50% 50%",
    "background_repeat": "no-repeat",
    "background_size": "cover"
  }
});
    </script>
{% endblock %}

music/templates/music/search.html
{% extends 'main/base.html' %}
{% block songs_active %}active{% endblock %}
{% load static %}
{% load bootstrap4 %}
{% block title %}Results{% endblock %}

{% block content %}
{% bootstrap_css %}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>

<div class="albums-container container-fluid">
	<!-- Songs -->
	<div class="row">
		<div class="col-sm-12">
			<h3>Search for: {{ request.GET.q }}</h3>
		</div>

		<div class="col-sm-8 col-md-9">

			{% if results %}
			<table class="table">
				<thead>
					<td>Cover</td>
					<td>Album</td>
					<td>Title</td>
					<td>Play</td>
					<td>Favorite</td>
				</thead>

				<tbody>
					{% for song in results %}
					<tr>
						<td>
							{% if song.album.logo %}
								<img src="{{ song.album.logo.url }}" class="ui medium image">
							{% else %}
								No image to display.
							{% endif %}
						</td>
						<td>
							<h4>{{ song.album.title }}</h4>
							<br>{{ song.album.artist }}
							<br>{{ song.album.year }}
						</td>
						<td>
							{{ song.title }}
						</td>
						<td>
							{% if song.file %}
							<audio controls>
								<source src="{{ song.file.url }}">
							</audio>
							{% else %}
								No file uploaded.
							{% endif %}
						</td>
						<td>
							<span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span>
						</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>

			{% else %}
			<p>No results were found.</p>
			{% endif %}
		</div>
	</div>
</div>
{% endblock %}

music/templates/music/songs.html
{% extends 'main/base.html' %}
{% block songs_active %}active{% endblock %}
{% load static %}
{% load bootstrap4 %}

{% block content %}
{% bootstrap_css %}
<div class="albums-container container-fluid">
	<!-- Songs -->
	<div class="row">
		<div class="col-sm-12">
			<h3>{{ user.username }}'s Songs</h3>
		</div>
		<div class="col-sm-8 col-md-9">
			{% if all_songs %}
			<ul>
				{% for song in all_songs %}
				<li><b>{{ song.album.artist }}</b> - <i>{{ song.album.title }}</i> - {{ song.title }}</li>
				{% endfor %}
			</ul>
			{% else %}
			<p>No songs have been added.</p>
			{% endif %}
		</div>
	</div>
</div>
{% endblock %}