gallery/urls.py
from django.urls import path
from gallery.views import ImageView, DownloadView
app_name = 'gallery'

urlpatterns = [
    path('', ImageView.as_view(), name='gallery'),
    path('download/', DownloadView.as_view(), name='download'),
]

messenger/urls.py
from django.urls import path
from messenger import views

app_name = 'messenger'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('new/', views.new, name='new_message'),
    path('send/', views.send, name='send_message'),
    path('users/', views.users, name='users_message'),
    path('<username>/', views.messages, name='messages')
]

music/urls.py
from django.urls import path
from music import views

app_name = 'music'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('songs/', views.SongView.as_view(), name='songs'),
    path('album/add/', views.AlbumCreateView.as_view(), name='album-add'),
    path('album/<pk>/update/', views.AlbumUpdateView.as_view(), name='album-update'),
    path('album/<pk>/favorite/', views.establish_favorite_album, name='album-favorite'),
    path('album/<pk>/delete/', views.AlbumDeleteView.as_view(), name='album-delete'),
    path('album/<pk>/detail/', views.AlbumDetailVew.as_view(), name='detail'),
    path('song/<pk>/add/', views.SongCreateView.as_view(), name='song-add'),
    path('song/<pk>/<song_id>/update/', views.SongUpdateView.as_view(), name='song-update'),
    path('song/<pk>/<song_id>/favorite/', views.establish_favorite_song, name='song-favorite'),
    path('song/<pk>/<song_id>/delete/', views.SongDeleteView.as_view(), name='song-delete'),
    path('search/', views.SearchListView.as_view(), name='search')
]

network/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('posts/', include('posts.urls')),
    path('accounts/', include('allauth.urls')),
    path('messenger/', include('messenger.urls')),
    path('gallery/', include('gallery.urls')),
    path('music/', include('music.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from posts import views

app_name = 'posts'

urlpatterns = [
    path('', views.create_post_comment, name='main'),
    path('like_post/', views.like_unlike_post, name='like_post'),
    path('delete/<pk>', views.PostDeleteView.as_view(), name='post_delete'),
    path('update/<pk>', views.PostUpdateView.as_view(), name='post_update'),
]

users/urls.py
from django.urls import path
from users import views

app_name = 'users'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('profile/', views.user_profile, name='profile'),
    path('my_invites/', views.invites_received, name='my_invites'),
    path('all_profiles/', views.ProfileListView.as_view(), name='all_profiles'),
    path('<slug>/', views.ProfileDetailView.as_view(), name='profile_detail'),
    path('available/invites/', views.ProfileInviteListView.as_view(), name='invite_profiles'),
    path('send_invite', views.send_invitation, name='send_invite'),
    path('remove_friend', views.remove_from_friends, name='remove_friend'),
    path('my_invites/accept', views.accept_invitation, name='accept_invitation'),
    path('my_invites/reject', views.reject_invitation, name='reject_invitation'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.db.models import Q
from django.shortcuts import reverse
from users.utils import get_random_number
from network import settings
import os
import hashlib, urllib


class ProfileManager(models.Manager):
    def get_all_profiles(self, me):
        profiles = Profile.objects.all().exclude(user=me)
        return profiles

    def get_all_profiles_to_invite(self, sender):
        profiles = Profile.objects.all().exclude(user=sender)
        profile = Profile.objects.get(user=sender)
        queryset = Relationship.objects.filter(Q(sender=profile) | Q(receiver=profile))

        accepted = set([])
        for rel in queryset:
            if rel.status == 'accepted':
                accepted.add(rel.receiver)
                accepted.add(rel.sender)

        available = [profile for profile in profiles if profile not in accepted]
        return available


class Profile(models.Model):
    """
    The page of the user, this one is created whenever a new user signs up.
    """
    first_name = models.CharField(max_length=150, db_index=True)
    last_name = models.CharField(max_length=150, db_index=True)
    email = models.EmailField(max_length=150, db_index=True)
    country = models.CharField(max_length=150, db_index=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(db_index=True, default='No information...', max_length=550)
    status = models.CharField(max_length=60, db_index=True)
    friends = models.ManyToManyField(User, db_index=True, blank=True, related_name='friends')
    image = models.ImageField(upload_to='images', default='images/avatar.jpg')
    slug = models.SlugField(unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = ProfileManager()

    def __str__(self):
        return f"{self.user.username}-{self.created_at.strftime('%d-%m-%Y')}"

    def get_absolute_url(self):
        return reverse('users:profile_detail', kwargs={"slug": self.slug})

    def get_friends(self):
        return self.friends.all()[:6]

    def get_friends_list(self):
        return self.friends.all().count()

    def get_posts_list(self):
        return self.posts.all().count()

    def get_posts(self):
        return self.posts.all()[:4]

    def get_all_authors_posts(self):
        return self.posts.all()

    def get_given_likes_list(self):
        likes = self.like_set.all()
        total_liked = 0
        for item in likes:
            if item.value == 'Like':
                total_liked += 1
        return total_liked

    def get_received_likes_list(self):
        posts = self.posts.all()
        total_liked = 0
        for item in posts:
            total_liked += item.liked.all().count()
        return total_liked

    def get_screen_name(self):
        try:
            if self.user.get_full_name():
                return self.user.get_full_name()
            else:
                return self.user.username
        except:
            return self.user.username

    # instead of image

    __initial_first_name = None
    __initial_last_name = None

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__initial_first_name = self.first_name
        self.__initial_last_name = self.last_name

    def save(self, *args, **kwargs):
        ex = False
        to_slug = self.slug
        if self.first_name != self.__initial_first_name or self.last_name != self.__initial_last_name or self.slug=="":
            if self.first_name and self.last_name:
                to_slug = slugify(str(self.first_name) + " " + str(self.last_name))
                ex = Profile.objects.filter(slug=to_slug).exists()
                while ex:
                    to_slug = slugify(to_slug + " " + str(get_random_number()))
                    ex = Profile.objects.filter(slug=to_slug).exists()
            else:
                to_slug = str(self.user)
        self.slug = to_slug
        super().save(*args, **kwargs)


STATUS_CHOICES = (
    ('send', 'send'),
    ('accepted', 'accepted')
)


class RelationshipManager(models.Manager):

    def invitations_received(self, receiver):
        queryset = Relationship.objects.filter(receiver=receiver, status='send')
        return queryset


class Relationship(models.Model):
    """
    Model for operations connected with user's friends, actions: send, receive, delete
    """
    sender = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='receiver')
    status = models.CharField(max_length=16, choices=STATUS_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = RelationshipManager()

    def __str__(self):
        return f"{self.sender}-{self.receiver}-{self.status}"

users/forms.py
from django import forms
from users.models import Profile


class ProfileModelForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('first_name', 'last_name', 'status', 'country', 'bio', 'image')

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from users.models import Profile, Relationship
from users.forms import ProfileModelForm


def home(request):
    return render(request, 'main/home.html')

@login_required
def user_profile(request):
    profile = Profile.objects.get(user=request.user)
    form = ProfileModelForm(request.POST or None, request.FILES or None, instance=profile)
    confirm = False

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            confirm = True
    context = {
        'profile': profile,
        'form': form,
        'confirm': confirm,
    }
    return render(request, 'users/profile.html', context)

@login_required
def invites_received(request):
    profile = Profile.objects.get(user=request.user)
    queryset = Relationship.objects.invitations_received(profile)
    results = list(map(lambda x: x.sender, queryset))
    is_empty = False
    if len(results) == 0:
        is_empty = True
    context = {
        'queryset': results,
        'is_empty': is_empty
    }

    return render(request, 'users/my_invites.html', context)

@login_required
def accept_invitation(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        sender = Profile.objects.get(pk=pk)
        receiver = Profile.objects.get(user=request.user)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        if rel.status == 'send':
            rel.status = 'accepted'
            rel.save()
    return redirect('users:my_invites')

@login_required
def reject_invitation(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        sender = Profile.objects.get(pk=pk)
        receiver = Profile.objects.get(user=request.user)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        rel.delete()
    return redirect('users:my_invites')


class ProfileInviteListView(LoginRequiredMixin, ListView):
    model = Profile
    template_name = 'users/list_invitations.html'

    def get_queryset(self):
        queryset = Profile.objects.get_all_profiles_to_invite(self.request.user)
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        profile = Profile.objects.get(user=self.request.user)
        r_receiver = Relationship.objects.filter(sender=profile)
        r_sender = Relationship.objects.filter(receiver=profile)
        rel_receiver = []
        rel_sender = []
        for item in r_receiver:
            rel_receiver.append(item.receiver.user)
        for item in r_sender:
            rel_sender.append(item.sender.user)

        context['rel_receiver'] = rel_receiver
        context['rel_sender'] = rel_sender
        context['is_empty'] = False
        if len(self.get_queryset()) == 0:
            context['is_empty'] = True
        return context

@login_required
def profiles_list(request):
    user = request.user
    queryset = Profile.objects.get_all_profiles(user)

    context = {'queryset': queryset}

    return render(request, 'users/profiles_list.html', context)


class ProfileListView(LoginRequiredMixin, ListView):
    model = Profile
    template_name = 'users/profiles_list.html'

    def get_queryset(self):
        queryset = Profile.objects.get_all_profiles(self.request.user)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profile = Profile.objects.get(user=self.request.user)
        r_receiver = Relationship.objects.filter(sender=profile)
        r_sender = Relationship.objects.filter(receiver=profile)
        rel_receiver = []
        rel_sender = []
        for item in r_receiver:
            rel_receiver.append(item.receiver.user)
        for item in r_sender:
            rel_sender.append(item.sender.user)

        context['rel_receiver'] = rel_receiver
        context['rel_sender'] = rel_sender
        context['is_empty'] = False
        if len(self.get_queryset()) == 0:
            context['is_empty'] = True
        return context


class ProfileDetailView(LoginRequiredMixin, DetailView):
    model = Profile
    template_name = 'users/detail.html'

    def get_object(self, slug=None):
        slug = self.kwargs.get('slug')
        profile = Profile.objects.get(slug=slug)
        return profile

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profile = Profile.objects.get(user=self.request.user)
        rel_r = Relationship.objects.filter(sender=profile)
        rel_s = Relationship.objects.filter(receiver=profile)
        rel_receiver = []
        rel_sender = []
        for item in rel_r:
            rel_receiver.append(item.receiver.user)
        for item in rel_s:
            rel_sender.append(item.sender.user)
        context["rel_receiver"] = rel_receiver
        context["rel_sender"] = rel_sender
        context['posts'] = self.get_object().get_all_authors_posts()
        context['len_posts'] = True if len(self.get_object().get_all_authors_posts()) > 0 else False
        return context

@login_required
def send_invitation(request):
   if request.method == 'POST':
       pk = request.POST.get('profile_pk')
       user = request.user
       sender = Profile.objects.get(user=user)
       receiver = Profile.objects.get(pk=pk)

       rel = Relationship.objects.create(sender=sender, receiver=receiver, status='send')

       return redirect(request.META.get('HTTP_REFERER'))
   return redirect('users:profile')

@login_required
def remove_from_friends(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)

        rel = Relationship.objects.filter(
            (Q(sender=sender) & Q(receiver=receiver)) | (Q(sender=receiver) & Q(receiver=sender))
        )
        rel.delete()
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('users:profile')

users/templates/main/base.html
{% load bootstrap4 %}
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <!--Custom css-->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'profile.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'messenger.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'signup.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'signin.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'navbar.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'gallery.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'music.css' %}">
    <script src="{% static 'load_more.js' %}"></script>

    <link href="https://getbootstrap.com/examples/jumbotron-narrow/jumbotron-narrow.css" rel="stylesheet">
    <!-- semantic UI -->
    <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>


    <!--  Font-awesome  -->
    <link href="https://fonts.googleapis.com/css?family=Great+Vibes|Open+Sans|Playfair+Display" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <link href="{% static 'fonts/fontawesome-all.min.css' %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>TeamCozy - {% block title %}{% endblock title %}</title>


    {% bootstrap_javascript jquery='full' %}

  </head>
  <body>
    {% include 'main/navbar.html' %}
    <div class="ui container">
      {% block content %}
      {% endblock content %}
    </div>

    {% block scripts %}
    {% endblock scripts %}

   <!--Custom js ADD-->
   <script type="text/javascript" src="{% static 'main.js' %}"></script>

  </body>
</html>

users/templates/main/home.html
{% extends 'main/base.html' %}
{% load i18n %}
{% load account socialaccount %}
{% block head_title %}{% trans "Sign In" %}{% endblock %}

{% block title %}
  Home
{% endblock title %}

{% block content %}
<head>
  <meta charset="UTF-8">
  <title>Messenger</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css">
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>
  <link rel="stylesheet" href="style.css"/>
</head>

<body>
  <div class="ui container">
    <img class="ui big right floated image" src="https://lifeposi.ru/wp-content/uploads/2021/08/adobestock_105395097-3-scaled-1.jpeg" alt="messenger logo">
  </div>
</div>

<div class="ui middle container">
  <h1> Be together,
    <p>whenever.</p>
  </h1>
  <h4>
    A simple way to text, communicate and
    <p>plan things all in one place.</p>
  </h4>

  <h4>
    <p>Welcome to TeamCozy!</p>
    <p>Here you can sign up and start your unforgettable journey!</p>
    <p>You can do plenty of things with us!</p>
    <p>You can get an invaluable experience of communicating!</p>
    <p>You can do whatever you want!</p>
<!--  Maybe button better  -->
    {% if request.user.is_authenticated %}
      <p>Sign up right now and get started your journey!</p>
      <p>Or sign in if you already have an account...</p>
    {% else %}
     <p><a href="{% url 'account_signup' %}">Sign up</a> right now and get started your journey!</p>
      Or <a href="{% url 'account_login' %}">sign in</a> if you already have an account...
    {% endif %}
  </h4>

<div class="ui fluid bottom container">
  <h1 style="text-align: center; padding: 70px; margin: 10px;">
    <p>So many ways to connect with all your friends</p>
  </h1>

  <div class="ui four column grid">
    <div class="column">
    <div class="ui centered card">
      <div class="image">
        <img style="border-radius: 30px;" src="https://static.twentyoverten.com/5d94b04c6e5bfa373f3b2a52/9yXLjJ1NXvX/iStock-913582690.jpg" alt="pic 1">
      </div>
      <div class="content">
        <a class="center aligned header">Communicate with your friends</a>

        <div class="center aligned description">
          Easily find your friends and start communication
        </div>
      </div>
    </div>
  </div>

    <div class="column">
      <div class="ui centered card">
        <div class="image">
          <img style="border-radius: 30px;" src="https://avatars.mds.yandex.net/i?id=f7087555174774a0b566b2202d3da67e-5869038-images-thumbs&n=13" alt="pic 2">
        </div>
        <div class="content">
          <a class="center aligned header">Establish contacts and have fun</a>
          <div class="center aligned description">
            See people, send an invitation and communicate. It's the closest to hanging out.
          </div>
        </div>
      </div>
    </div>

    <div class="column">
      <div class="ui centered card">
        <div class="image">
          <img style="border-radius: 30px;" src="https://avatars.mds.yandex.net/i?id=a85ff898c45a8763021ae68b5e961a78-5877464-images-thumbs&n=13" alt="pic 3">
        </div>
        <div class="content">
          <a class="center aligned header">Upload your posts</a>
          <div class="center aligned description">
            Write your posts, choose whatever your want and then upload so that other people see it
          </div>
        </div>
      </div>
    </div>

    <div class="column">
      <div class="ui centered card">
        <div class="image">
          <img style="border-radius: 30px;" src="https://thumbs.dreamstime.com/b/digital-picture-gallery-close-up-laptop-pictures-blurry-dark-background-media-photo-double-exposure-164122614.jpg" alt="pic 4">
        </div>
        <div class="content">
          <a class="center aligned header">Create your gallery</a>
          <div class="center aligned description">
           Upload any images in your gallery and share it with your friends
          </div>
        </div>
      </div>
    </div>

<script>
  $('.ui.checkbox')
      .checkbox();
</script>
<script>
  $('.ui.dropdown')
      .dropdown();
</script>

</body>
{% endblock content %}

{% block scripts %}
<script>
    $(document).ready(function(){
      console.log('working')
    })
</script>
{% endblock scripts %}

users/templates/main/navbar.html
{% load static %}
{% load bootstrap4 %}

{% url 'posts:main' as path_to_posts %}
{% url 'users:home' as path_to_home %}
{% url 'users:all_profiles' as path_to_all_profiles %}
{% url 'users:profile' as path_to_my_profile %}
{% url 'users:my_invites' as path_to_my_invites %}
{% url 'users:invite_profiles' as path_to_invites %}
{% url 'messenger:inbox' as path_to_messages %}
{% url 'gallery:gallery' as path_to_gallery %}
{% url 'music:index' as path_to_music %}

<div class="ui inverted menu nav mb-7">
  <div class="ui container">
    <a href="{{path_to_home}}" class="{% if request.path == path_to_home %}active{% endif %} item">
        <h3>TeamCozy</h3>
    </a>
    {% if request.user.is_authenticated %}
    <a href="{{path_to_posts}}" class="{% if request.path == path_to_posts %}active{% endif %} item">
        Board
    </a>

    <a href="{{path_to_messages}}" class="{% if request.path == path_to_messages %}active{% endif %} item">
        Messages
    </a>
    <a href="{{path_to_gallery}}" class="{% if request.path == path_to_gallery %}active{% endif %} item">
        Gallery
    </a>

    {% endif %}
    <div class="right menu">
        {% if request.user.is_authenticated %}
        <div class="item">
            <div class="ui floating dropdown icon button teal"> Friends
                <i class="dropdown icon"></i>
                <div class="menu">
                    <a href="{{path_to_all_profiles}}" class="{% if request.path == path_to_all_profiles %}active{% endif %} item">
                        All Profiles
                    </a>
                    <a href="{{path_to_invites}}" class="{% if request.path == path_to_invites %}active{% endif %} item">
                        Send Invites
                    </a>
                    <a href="{{path_to_my_invites}}" class="{% if request.path == path_to_my_invites %}active{% endif %} item">
                        Received Invites &nbsp; <div class="ui purple horizontal label">{{invites_num}}</div>
                    </a>
                </div>
             </div>
        </div>
             <div class="item">
              <form action="{% url 'music:search' %}" method="GET">
                <div class="ui action left icon input">
                <input class="prompt" type="text" name='q' placeholder="song title...">
                <i class="search icon"></i>
                <button type='submit' class="ui button">Search</button>
                </div>
              </form>
            </div>

            <a href="{{path_to_my_profile}}" class="{% if request.path == path_to_my_profile %}active{% endif %} item">
                <img src={{picture.url}} class="ui avatar image">&nbsp;
                 {{ request.user }}
            </a>
               <a href="{{path_to_music}}" class="{% if request.path == path_to_music %}active{% endif %} item">
                 Music
               </a>

            <a href="{% url 'account_logout' %}" class="ui item">
                Logout
            </a>

        {% else %}
         <a href="{% url 'account_signup' %}" class="ui item">
            Sign up
        </a>
        <a href="{% url 'account_login' %}" class="ui item">
            Login
        </a>
        {% endif %}
    </div>
  </div>
</div>