messenger/urls.py
from django.urls import path
from messenger import views

app_name = 'messenger'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('new/', views.new, name='new_message'),
    path('send/', views.send, name='send_message'),
    path('users/', views.users, name='users_message'),
    path('<username>/', views.messages, name='messages')
]

music/urls.py
from django.urls import path
from music import views

app_name = 'music'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('songs/', views.SongView.as_view(), name='songs'),
    path('album/add/', views.AlbumCreateView.as_view(), name='album-add'),
    path('album/<pk>/update/', views.AlbumUpdateView.as_view(), name='album-update'),
    path('album/<pk>/favorite/', views.establish_favorite_album, name='album-favorite'),
    path('album/<pk>/delete/', views.AlbumDeleteView.as_view(), name='album-delete'),
    path('album/<pk>/detail/', views.AlbumDetailVew.as_view(), name='detail'),
    path('song/<pk>/add/', views.SongCreateView.as_view(), name='song-add'),
    path('song/<pk>/<song_id>/update/', views.SongUpdateView.as_view(), name='song-update'),
    path('song/<pk>/<song_id>/favorite/', views.establish_favorite_song, name='song-favorite'),
    path('song/<pk>/<song_id>/delete/', views.SongDeleteView.as_view(), name='song-delete'),
    path('search/', views.SearchListView.as_view(), name='search')
]

network/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('posts/', include('posts.urls')),
    path('accounts/', include('allauth.urls')),
    path('messenger/', include('messenger.urls')),
    path('gallery/', include('gallery.urls')),
    path('music/', include('music.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

messenger/models.py
from django.db import models
from django.db.models import Max
from django.contrib.auth.models import User


class Message(models.Model):
    """
    Class for creating message system
    """
    user = models.ForeignKey(User, related_name='+', on_delete=models.CASCADE)
    conversation = models.ForeignKey(User, related_name='+', on_delete=models.CASCADE)
    from_user = models.ForeignKey(User, related_name='+', on_delete=models.CASCADE)
    message = models.TextField(max_length=1050, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = 'Messages'
        ordering = ('date',)

    def __str__(self):
        return self.message

    @staticmethod
    def send_message(from_user, to_user, message):
        message = message[:1050]
        current_user_message = Message(from_user=from_user,
            message=message,
            user=from_user,
            conversation=to_user,
            is_read=True
        )
        current_user_message.save()
        Message(from_user=from_user,
             conversation=from_user,
             message=message,
             user=to_user).save()
        return current_user_message

    @staticmethod
    def get_conversations(user):
        conversations = Message.objects.filter(user=user).values('conversation').annotate(last=Max('date')).order_by('-last')
        users = []
        for conversation in conversations:
            users.append({
               'user': User.objects.get(pk=conversation['conversation']),
               'last': conversation['last'],
                'unread': Message.objects.filter(user=user, conversation__pk=conversation['conversation'], is_read=False).count(),

            })
        return users

messenger/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseBadRequest
from django.contrib.auth.models import User
from messenger.models import Message
import json


@login_required
def inbox(request):
    conversations = Message.get_conversations(user=request.user)
    active_conversation = None
    messages = None
    if conversations:
        conversation = conversations[0]
        active_conversation = conversation['user'].username
        messages = Message.objects.filter(user=request.user, conversation=conversation['user'])
        messages.update(is_read=True)
        for conversation in conversations:
            if conversation['user'].username == active_conversation:
                conversation['unread'] = 0

    context = {
        'messages': messages,
        'conversations': conversations,
        'active': active_conversation
    }
    return render(request, 'messenger/inbox.html', context)

@login_required
def messages(request, username):
    conversations = Message.get_conversations(user=request.user)
    active_conversation = username
    mes = Message.objects.filter(user=request.user, conversation__username=username)
    mes.update(is_read=True)
    for conversation in conversations:
        if conversation['user'].username == username:
            conversation['unread'] = 0
    context = {
        'messages': mes,
        'conversations': conversations,
        'active': active_conversation
    }
    return render(request, 'messenger/inbox.html', context)

@login_required
def new(request):
    if request.method == 'POST':
        from_user = request.user
        to_user_username = request.POST.get('to')
        try:
            to_user = User.objects.get(username=to_user_username)
        except Exception:
            try:
                to_user_username = to_user_username[to_user_username.rfind('(') + 1:len(to_user_username) -1]
                to_user = User.objects.get(username=to_user_username)
            except Exception:
                return redirect('/messages/new')
        message = request.POST.get('message')
        if len(message.strip()) == 0:
            return redirect('/messages/new')
        if from_user != to_user:
            Message.send_message(from_user, to_user, message)
        return redirect('messenger:inbox')
    else:
        conversations = Message.get_conversations(user=request.user)
        context = {'conversations': conversations}
        return render(request, 'messenger/new.html', context)

@login_required
def send(request):
    if request.method == 'POST':
        from_user = request.user
        to_user_username = request.POST.get('to')
        to_user = User.objects.get(username=to_user_username)
        message = request.POST.get('message')
        if len(message.strip()) == 0:
            return redirect('messenger:inbox')
        if from_user != to_user:
            msg = Message.send_message(from_user, to_user, message)
            return redirect(request.META.get('HTTP_REFERER'))
        return HttpResponse()
    else:
        return HttpResponseBadRequest()

@login_required
def users(request):
    users = User.objects.filter(is_active=True)
    dump = []
    template = u'{0} ({1})'
    for user in users:
        if user.profile.get_screen_name() != user.username:
            dump.append(template.format(user.profile.get_screen_name(), user.username))
        else:
            dump.append(user.username)
    data = json.dumps(dump)
    return HttpResponse(data, content_type='application/json')

messenger/templates/messenger/inbox.html
{% extends 'main/base.html' %}
{% load i18n %}
{% load static %}
{% load bootstrap4 %}

{% block title %}{% trans 'Inbox' %}{% endblock %}

{% block page_header %}{% trans 'Inbox' %}{% endblock %}

{% block content %}
{% bootstrap_css %}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>

<div class="container">
<div class="ks-page-content">
    <div class="ks-page-content-body">
        <div class="ks-messenger">
            <div class="ks-discussions">
                <div class="ks-search">
                    <div class="input-icon icon-right icon icon-lg icon-color-primary">
                        <input id="input-group-icon-text" type="text" class="form-control" placeholder="Search">
                        <span class="icon-addon">
                        <span class="la la-search"></span>
                        </span>
                    </div>
                </div>
                <div class="ks-body ks-scrollable jspScrollable" data-auto-height="" style="height: 480px; overflow-y: auto; padding: 0px; width: 339px;" tabindex="0">
                    <div class="jspContainer" style="width: 339px; height: 550px;">
                        <div class="jspPane" style="padding: 0px; top: 0px; width: 329px;">
                            <ul class="ks-items">
                              {% for conversation in conversations %}
                              <li class="ks-item">
                                  <a href="{% url 'messenger:messages' conversation.user.username %}"
                                    class="list-group-item{% if active == conversation.user.username %} active{% endif %}">
                                    <span class="ks-avatar">
                                     <img src="{{ conversation.user.profile.image.url }}" width="36" height="36">
                                    </span>
                                    <div class="ks-body">
                                     <div class="ks-name">
                                      {{ conversation.user.profile.get_screen_name }}
                                      {% if conversation.unread > 0 %}
                                         <div class="ks-item ks-unread">
                                            <span class="badge pull-right">{{ conversation.unread }}</span>
                                         </div>
                                      {% endif %}                                      </div>
<!--                                <div class="ks-message">Why didn't he come and talk to me himse...</div>-->
                                    </div>
                                  </a>
                              </li>
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="jspVerticalBar">
                            <div class="jspCap jspCapTop"></div>
                            <div class="jspTrack" style="height: 550px;">
                                <div class="jspDrag" style="height: 261px;">
                                    <div class="jspDragTop"></div>
                                    <div class="jspDragBottom"></div>
                                </div>
                            </div>
                            <div class="jspCap jspCapBottom"></div>
                        </div>
                    </div>
                </div>
                 <div class="page-header">
                      <a href="{% url 'messenger:new_message' %}" class="btn btn btn-primary new-message"> <i class="fa fa-envelope"></i> New Message </a>
                 </div>
            </div>

            <div class="ks-messages ks-messenger__messages">
                <div class="ks-header">
                    <div class="ks-description">
                        <div class="ks-name">Your chat</div>
                    </div>
                </div>
                <div class="ks-body ks-scrollable jspScrollable" data-auto-height="" data-reduce-height=".ks-footer" data-fix-height="32" style="height: 480px; overflow-y: auto; padding: 0px; width: 701px;" tabindex="0">
                    <div class="jspContainer" style="width: 701px; height: 481px;">
                        <div class="jspPane" style="padding: 0px; top: 0px; width: 691px;">
                            <ul class="ks-items">
                              {% for message in messages %}
                                <li class="ks-item ks-self">
                                    {% include 'messenger/messages.html' with message=message %}
                                </li>
                              {% endfor %}
                            </ul>
                        </div>
                        <div class="jspVerticalBar">
                            <div class="jspCap jspCapTop"></div>
                            <div class="jspTrack" style="height: 481px;">
                                <div class="jspDrag" style="height: 206px;">
                                    <div class="jspDragTop"></div>
                                    <div class="jspDragBottom"></div>
                                </div>
                            </div>
                            <div class="jspCap jspCapBottom"></div>
                        </div>
                    </div>
                </div>
                <form class="send-message" method="post" action="{% url 'messenger:send_message' %}" id="send">
                  <div style="margin-top: .3em">
                      {% csrf_token %}
                      <input type="hidden" name="to" value="{{ active }}">
                      <input class="form-control" type="text" name="message" placeholder="Type something..." maxlength="1000" autocomplete="off">
                  </div>
                </form>
            </div>

        </div>
    </div>
</div>
</div>
{% endblock content %}

messenger/templates/messenger/messages.html
<span class="ks-avatar ks-offline">
    <a href="{{message.from_user.profile.get_absolute_url}}"><img src="{{ message.from_user.profile.image.url }}" width="36" height="36" class="rounded-circle"></a>
</span>
<div class="ks-body">
    <div class="ks-header">
        <span class="ks-name">{{ message.from_user.profile.get_screen_name }}</span>
        <span class="ks-datetime">{{ message.date|date:'N d G:i' }}</span>
    </div>
    <div class="ks-message">{{ message.message }}</div>
</div>

messenger/templates/messenger/new.html
{% extends 'main/base.html' %}
{% load static %}
{% load i18n %}
{% load bootstrap4 %}


{% block title %}{% trans 'New message' %}{% endblock %}

{% block page_header %}{% trans 'New message' %}{% endblock %}

{% block content %}
{% bootstrap_css %}
  <form class="form-horizontal" role="form" method="POST">
    {% csrf_token %}
    <div class="form-group">
      <label for="to" class="col-sm-1 control-label">To</label>
      <div class="col-sm-11">
        <input class="form-control typeahead" type="text" id="to" name="to">
      </div>
    </div>
    <div class="form-group">
      <label for="to" class="col-sm-1 control-label">Message</label>
      <div class="col-sm-11">
        <textarea class="form-control" id="message" name="message" placeholder="Write a message..." rows="4"></textarea>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-11 col-sm-offset-1">
        <button type="submit" class="btn btn-primary">Send</button>
      </div>
    </div>
  </form>
  <script src="{% static 'messages.typehead.js' %}"></script>
{% endblock content %}