music/urls.py
from django.urls import path
from music import views

app_name = 'music'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('songs/', views.SongView.as_view(), name='songs'),
    path('album/add/', views.AlbumCreateView.as_view(), name='album-add'),
    path('album/<pk>/update/', views.AlbumUpdateView.as_view(), name='album-update'),
    path('album/<pk>/favorite/', views.establish_favorite_album, name='album-favorite'),
    path('album/<pk>/delete/', views.AlbumDeleteView.as_view(), name='album-delete'),
    path('album/<pk>/detail/', views.AlbumDetailVew.as_view(), name='detail'),
    path('song/<pk>/add/', views.SongCreateView.as_view(), name='song-add'),
    path('song/<pk>/<song_id>/update/', views.SongUpdateView.as_view(), name='song-update'),
    path('song/<pk>/<song_id>/favorite/', views.establish_favorite_song, name='song-favorite'),
    path('song/<pk>/<song_id>/delete/', views.SongDeleteView.as_view(), name='song-delete'),
    path('search/', views.SearchListView.as_view(), name='search')
]

network/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('posts/', include('posts.urls')),
    path('accounts/', include('allauth.urls')),
    path('messenger/', include('messenger.urls')),
    path('gallery/', include('gallery.urls')),
    path('music/', include('music.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users import views

app_name = 'users'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('profile/', views.user_profile, name='profile'),
    path('my_invites/', views.invites_received, name='my_invites'),
    path('all_profiles/', views.ProfileListView.as_view(), name='all_profiles'),
    path('<slug>/', views.ProfileDetailView.as_view(), name='profile_detail'),
    path('available/invites/', views.ProfileInviteListView.as_view(), name='invite_profiles'),
    path('send_invite', views.send_invitation, name='send_invite'),
    path('remove_friend', views.remove_from_friends, name='remove_friend'),
    path('my_invites/accept', views.accept_invitation, name='accept_invitation'),
    path('my_invites/reject', views.reject_invitation, name='reject_invitation'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.db.models import Q
from django.shortcuts import reverse
from users.utils import get_random_number
from network import settings
import os
import hashlib, urllib


class ProfileManager(models.Manager):
    def get_all_profiles(self, me):
        profiles = Profile.objects.all().exclude(user=me)
        return profiles

    def get_all_profiles_to_invite(self, sender):
        profiles = Profile.objects.all().exclude(user=sender)
        profile = Profile.objects.get(user=sender)
        queryset = Relationship.objects.filter(Q(sender=profile) | Q(receiver=profile))

        accepted = set([])
        for rel in queryset:
            if rel.status == 'accepted':
                accepted.add(rel.receiver)
                accepted.add(rel.sender)

        available = [profile for profile in profiles if profile not in accepted]
        return available


class Profile(models.Model):
    """
    The page of the user, this one is created whenever a new user signs up.
    """
    first_name = models.CharField(max_length=150, db_index=True)
    last_name = models.CharField(max_length=150, db_index=True)
    email = models.EmailField(max_length=150, db_index=True)
    country = models.CharField(max_length=150, db_index=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(db_index=True, default='No information...', max_length=550)
    status = models.CharField(max_length=60, db_index=True)
    friends = models.ManyToManyField(User, db_index=True, blank=True, related_name='friends')
    image = models.ImageField(upload_to='images', default='images/avatar.jpg')
    slug = models.SlugField(unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = ProfileManager()

    def __str__(self):
        return f"{self.user.username}-{self.created_at.strftime('%d-%m-%Y')}"

    def get_absolute_url(self):
        return reverse('users:profile_detail', kwargs={"slug": self.slug})

    def get_friends(self):
        return self.friends.all()[:6]

    def get_friends_list(self):
        return self.friends.all().count()

    def get_posts_list(self):
        return self.posts.all().count()

    def get_posts(self):
        return self.posts.all()[:4]

    def get_all_authors_posts(self):
        return self.posts.all()

    def get_given_likes_list(self):
        likes = self.like_set.all()
        total_liked = 0
        for item in likes:
            if item.value == 'Like':
                total_liked += 1
        return total_liked

    def get_received_likes_list(self):
        posts = self.posts.all()
        total_liked = 0
        for item in posts:
            total_liked += item.liked.all().count()
        return total_liked

    def get_screen_name(self):
        try:
            if self.user.get_full_name():
                return self.user.get_full_name()
            else:
                return self.user.username
        except:
            return self.user.username

    # instead of image

    __initial_first_name = None
    __initial_last_name = None

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__initial_first_name = self.first_name
        self.__initial_last_name = self.last_name

    def save(self, *args, **kwargs):
        ex = False
        to_slug = self.slug
        if self.first_name != self.__initial_first_name or self.last_name != self.__initial_last_name or self.slug=="":
            if self.first_name and self.last_name:
                to_slug = slugify(str(self.first_name) + " " + str(self.last_name))
                ex = Profile.objects.filter(slug=to_slug).exists()
                while ex:
                    to_slug = slugify(to_slug + " " + str(get_random_number()))
                    ex = Profile.objects.filter(slug=to_slug).exists()
            else:
                to_slug = str(self.user)
        self.slug = to_slug
        super().save(*args, **kwargs)


STATUS_CHOICES = (
    ('send', 'send'),
    ('accepted', 'accepted')
)


class RelationshipManager(models.Manager):

    def invitations_received(self, receiver):
        queryset = Relationship.objects.filter(receiver=receiver, status='send')
        return queryset


class Relationship(models.Model):
    """
    Model for operations connected with user's friends, actions: send, receive, delete
    """
    sender = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='receiver')
    status = models.CharField(max_length=16, choices=STATUS_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = RelationshipManager()

    def __str__(self):
        return f"{self.sender}-{self.receiver}-{self.status}"

users/forms.py
from django import forms
from users.models import Profile


class ProfileModelForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('first_name', 'last_name', 'status', 'country', 'bio', 'image')

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from users.models import Profile, Relationship
from users.forms import ProfileModelForm


def home(request):
    return render(request, 'main/home.html')

@login_required
def user_profile(request):
    profile = Profile.objects.get(user=request.user)
    form = ProfileModelForm(request.POST or None, request.FILES or None, instance=profile)
    confirm = False

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            confirm = True
    context = {
        'profile': profile,
        'form': form,
        'confirm': confirm,
    }
    return render(request, 'users/profile.html', context)

@login_required
def invites_received(request):
    profile = Profile.objects.get(user=request.user)
    queryset = Relationship.objects.invitations_received(profile)
    results = list(map(lambda x: x.sender, queryset))
    is_empty = False
    if len(results) == 0:
        is_empty = True
    context = {
        'queryset': results,
        'is_empty': is_empty
    }

    return render(request, 'users/my_invites.html', context)

@login_required
def accept_invitation(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        sender = Profile.objects.get(pk=pk)
        receiver = Profile.objects.get(user=request.user)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        if rel.status == 'send':
            rel.status = 'accepted'
            rel.save()
    return redirect('users:my_invites')

@login_required
def reject_invitation(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        sender = Profile.objects.get(pk=pk)
        receiver = Profile.objects.get(user=request.user)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        rel.delete()
    return redirect('users:my_invites')


class ProfileInviteListView(LoginRequiredMixin, ListView):
    model = Profile
    template_name = 'users/list_invitations.html'

    def get_queryset(self):
        queryset = Profile.objects.get_all_profiles_to_invite(self.request.user)
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        profile = Profile.objects.get(user=self.request.user)
        r_receiver = Relationship.objects.filter(sender=profile)
        r_sender = Relationship.objects.filter(receiver=profile)
        rel_receiver = []
        rel_sender = []
        for item in r_receiver:
            rel_receiver.append(item.receiver.user)
        for item in r_sender:
            rel_sender.append(item.sender.user)

        context['rel_receiver'] = rel_receiver
        context['rel_sender'] = rel_sender
        context['is_empty'] = False
        if len(self.get_queryset()) == 0:
            context['is_empty'] = True
        return context

@login_required
def profiles_list(request):
    user = request.user
    queryset = Profile.objects.get_all_profiles(user)

    context = {'queryset': queryset}

    return render(request, 'users/profiles_list.html', context)


class ProfileListView(LoginRequiredMixin, ListView):
    model = Profile
    template_name = 'users/profiles_list.html'

    def get_queryset(self):
        queryset = Profile.objects.get_all_profiles(self.request.user)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profile = Profile.objects.get(user=self.request.user)
        r_receiver = Relationship.objects.filter(sender=profile)
        r_sender = Relationship.objects.filter(receiver=profile)
        rel_receiver = []
        rel_sender = []
        for item in r_receiver:
            rel_receiver.append(item.receiver.user)
        for item in r_sender:
            rel_sender.append(item.sender.user)

        context['rel_receiver'] = rel_receiver
        context['rel_sender'] = rel_sender
        context['is_empty'] = False
        if len(self.get_queryset()) == 0:
            context['is_empty'] = True
        return context


class ProfileDetailView(LoginRequiredMixin, DetailView):
    model = Profile
    template_name = 'users/detail.html'

    def get_object(self, slug=None):
        slug = self.kwargs.get('slug')
        profile = Profile.objects.get(slug=slug)
        return profile

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profile = Profile.objects.get(user=self.request.user)
        rel_r = Relationship.objects.filter(sender=profile)
        rel_s = Relationship.objects.filter(receiver=profile)
        rel_receiver = []
        rel_sender = []
        for item in rel_r:
            rel_receiver.append(item.receiver.user)
        for item in rel_s:
            rel_sender.append(item.sender.user)
        context["rel_receiver"] = rel_receiver
        context["rel_sender"] = rel_sender
        context['posts'] = self.get_object().get_all_authors_posts()
        context['len_posts'] = True if len(self.get_object().get_all_authors_posts()) > 0 else False
        return context

@login_required
def send_invitation(request):
   if request.method == 'POST':
       pk = request.POST.get('profile_pk')
       user = request.user
       sender = Profile.objects.get(user=user)
       receiver = Profile.objects.get(pk=pk)

       rel = Relationship.objects.create(sender=sender, receiver=receiver, status='send')

       return redirect(request.META.get('HTTP_REFERER'))
   return redirect('users:profile')

@login_required
def remove_from_friends(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)

        rel = Relationship.objects.filter(
            (Q(sender=sender) & Q(receiver=receiver)) | (Q(sender=receiver) & Q(receiver=sender))
        )
        rel.delete()
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('users:profile')

users/templates/users/detail.html
{% extends 'main/base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block title %}
  profile detail
{% endblock title %}

{% block content %}
{% bootstrap_css %}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>
<div class="container">
    <div class="main-body">
          <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                    <img src="{{object.image.url}}" alt="Admin" class="rounded-circle" width="150">
                    <div class="mt-3">
                      <h4>{{object.user}}</h4>
                      <p class="text-secondary mb-1">{{object.status}}</p>
                      <p class="text-muted font-size-sm">{{object.country}}</p>
                      {% if object.user not in rel_receiver and object.user not in rel_sender %}
                        <form action="{% url 'users:send_invite' %}" method="POST">
                          {% csrf_token %}
                          <input type="hidden" name="profile_pk" value={{object.pk}}>
                          <button type="submit" class="btn btn-outline-success"><i class="plus square icon"></i>Add to friends</button>
                        </form>
                      {% endif %}

                      {% if object.user in rel_receiver and request.user not in object.friends.all %}
                        <a class="btn btn-secondary btn-lg disabled"><i class="user icon"></i>Waiting for approval</a>
                      {% endif %}

                      {% if request.user in object.friends.all %}
                        <form action="{% url 'users:remove_friend' %}" method="POST">
                          {% csrf_token %}
                          <input type="hidden" name="profile_pk" value={{object.pk}}>
                          <button type="submit" class="btn btn-danger"><i class="minus square icon"></i>Remove from friends</button>
                        </form>
                      {% endif %}
                    </div>
                  </div>
                </div>
              </div>
              <div class="card mt-3">
                <ul class="list-group list-group-flush">
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"> <img src="https://img.icons8.com/external-stick-figures-gan-khoon-lay/25/000000/external-friend-teamwork-stick-figures-gan-khoon-lay.png"/> Number of friends</h6>
                    <span class="text-secondary">{{profile.get_friends_list}}</span>
                  </li>
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"> <img src="https://img.icons8.com/external-soft-fill-juicy-fish/25/000000/external-posts-microservices-soft-fill-soft-fill-juicy-fish.png"/>  Number of posts</h6>
                    <span class="text-secondary">{{profile.get_posts_list}}</span>
                  </li>
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><img src="https://img.icons8.com/dotty/25/000000/give-gift.png"/>Number of likes given</h6>
                    <span class="text-secondary"> {{profile.get_given_likes_list}}</span>
                  </li>
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><img src="https://img.icons8.com/external-flaticons-flat-flat-icons/25/000000/external-like-modern-dating-flaticons-flat-flat-icons-3.png"/> Number of likes received</h6>
                    <span class="text-secondary">{{profile.get_received_likes_list}}</span>
                  </li>
                </ul>
              </div>
            </div>
            <div class="col-md-8">
              <div class="card mb-3">
                <div class="card-body">
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">First name</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{object.first_name}}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Last name</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{object.last_name}}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Email</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{object.email}}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Bio</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{object.bio}}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Country</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{object.country}}
                    </div>
                  </div>

                </div>
              </div>

              <div class="row gutters-sm">
                <div class="col-sm-6 mb-3">
                  <div class="card h-100">
                    <div class="card-body">
                      <h6 class="d-flex align-items-center mb-3">Friends</h6>
                      {% for friend in profile.get_friends %}
                        <div class="media">
                          <div class="media-left media-middle">
                            <a href="{{friend.profile.get_absolute_url}}"><img class="media-object img-circle img-thumbnail thumb48" src="{{friend.profile.image.url}}" alt="Contact"></a>
                          </div>
                          <div class="media-body pt-sm">
                            <div class="text-bold">{{friend}}
                              <div class="text-sm text-muted">{{friend.last_login}}</div>
                            </div>
                          </div>
                        </div>
                      {% endfor %}
                    </div>
                  </div>
                </div>
                <div class="col-sm-6 mb-3">
                  <div class="card h-100">
                    <div class="card-body">
                      <h6 class="d-flex align-items-center mb-3">Latest posts</h6>
                      {% for post in profile.get_posts %}
                        <div class="ui segment">{{post.content}}</div>
                      {% endfor %}
                    </div>

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
    </div>
{% endblock content %}

users/templates/users/friend_list.html
{% load static %}
{% block content %}
    {% for friend in object_list %}
       {{friend.first_name}}
    {% endfor %}
{% endblock content %}

users/templates/users/list_invitations.html
{% extends 'main/base.html' %}

{% block title %}
  invite friends
{% endblock title %}

{% block content %}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>
<ul>
    {% for obj in object_list %}
      <div class="ui segment">
          <div class="ui grid">
              <div class="row">
                  <div class="three wide column">
                      <img class="ui small circular image" src="{{obj.image.url}}">
                  </div>
                  <div class="thirteen wide column">
                      <h3>{{obj.user}}</h3>
                      <p>{{obj.bio}}</p>
                      <a href="{{obj.get_absolute_url}}"><button class="ui primary button w-big mb-5">See profile</button></a>
                      {% if obj.user not in rel_receiver and obj.user not in rel_sender %}
                            <form action="{% url 'users:send_invite' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="profile_pk" value={{obj.pk}}>
                                <button type="submit" class="ui positive basic button mb-5 w-big"><i class="plus square icon"></i>Add to friends</button>
                            </form>
                        {% endif %}

                      {% if obj.user in rel_receiver and request.user not in obj.friends.all %}
                          <button class="ui disabled button mb-5 w-big"><i class="user icon"></i>Waiting for approval</button>
                      {% endif %}
                  </div>
              </div>
          </div>
      </div>
    {% endfor %}
</ul>
{% endblock content %}

users/templates/users/my_invites.html
{% extends 'main/base.html' %}

{% block title %}
  my invites
{% endblock title %}

{% block content %}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>
    {% if is_empty %}
      <h1>No invitations here..</h1>
    {% endif %}
    {% for obj in queryset %}
      <div class="ui segment">
          <div class="ui grid">
              <div class="row">
                  <div class="three wide column">
                      <img class="ui small circular image" src="{{obj.image.url}}">
                  </div>
                  <div class="thirteen wide column">
                      <h3>{{obj.user}}</h3>
                      <p>{{obj.bio}}</p>
                      <a href="{{obj.get_absolute_url}}"><button class="ui primary button w-big mb-5">See profile</button></a>
                      <form action="{% url 'users:accept_invitation' %}" method="POST">
                          {% csrf_token %}
                          <input type="hidden" name="profile_pk" value="{{obj.pk}}">
                          <button type="submit" class="ui positive basic button w-big mb-5">
                              <i class="check icon"></i>
                              Accept invite
                          </button>
                      </form>
                      <form action="{% url 'users:reject_invitation' %}" method="POST">
                          {% csrf_token %}
                          <input type="hidden" name="profile_pk" value="{{obj.pk}}">
                          <button type="submit" class="ui negative basic button w-big mb-5">
                              <i class="close icon"></i>
                              Reject invite
                          </button>
                      </form>
                  </div>
              </div>
          </div>
      </div>
    {% endfor %}
{% endblock content %}

users/templates/users/profiles_list.html
{% extends 'main/base.html' %}

{% block title %}
  all profiles
{% endblock title %}


{% block content %}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>

    {% if is_empty %}
        <h1>No profiles to interact with</h1>
    {% endif %}

    {% for obj in object_list %}
        <div class="ui segment">
            <div class="ui grid">
                <div class="row">
                    <div class="three wide column">
                        <img class="ui small circular image" src={{obj.image.url}}>
                    </div>
                    <div class="thirteen wide column">
                        <h3>{{obj.user}}</h3>
                        <p>{{obj.bio}}</p>
                        <a href={{obj.get_absolute_url}}><button class="ui primary button mb-5 w-big">See profile</button></a>
                        <br>

                        {% if obj.user not in rel_receiver and obj.user not in rel_sender %}
                            <form action="{% url 'users:send_invite' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="profile_pk" value={{obj.pk}}>
                                <button type="submit" class="ui positive basic button mb-5 w-big"><i class="plus square icon"></i>Add to friends</button>
                            </form>
                        {% endif %}

                        {% if obj.user in rel_receiver and request.user not in obj.friends.all %}
                            <button class="ui disabled button mb-5 w-big"><i class="user icon"></i>Waiting for approval</button>
                        {% endif %}

                        {% if request.user in obj.friends.all %}
                        <form action="{% url 'users:remove_friend' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value={{obj.pk}}>
                            <button type="submit" class="ui negative basic button mb-5 w-big"><i class="minus square icon"></i>Remove from friends</button>
                        </form>
                        {% endif %}
                    </div>

                </div>
            </div>
        </div>
    {% endfor %}
{% endblock content %}